return {
  ['default'] = {
    main = 'Marin Staff +1',
    sub = 'Umbra Strap',
    ammo = 'Ghastly Tathlum +1',
    head = 'Nyame Helm',
    body = 'Nyame Mail',
    hands = 'Nyame Gauntlets',
    legs = 'Nyame Flanchard',
    feet = 'Nyame Sollerets',
    neck = 'Loricate Torque',
    waist = 'Embla Sash',
    left_ear = "Hecate's Earring",
    right_ear = 'Moldavite Earring',
    left_ring = 'Jhakri Ring',
    right_ring = 'Mallquis Ring',
    back = { name = 'Mecisto. Mantle', augments = { 'Cap. Point+49%', 'MND+1', 'Rng.Acc.+5', 'DEF+6' } },
  },
  ['refresh'] = {
    ammo = 'Ghastly Tathlum +1',
    head = 'Nyame Helm',
    body = 'Nyame Mail',
    hands = 'Nyame Gauntlets',
    legs = 'Nyame Flanchard',
    feet = 'Nyame Sollerets',
    neck = 'Loricate Torque',
    waist = 'Embla Sash',
    left_ear = "Hecate's Earring",
    right_ear = 'Moldavite Earring',
    left_ring = 'Mallquis Ring',
    right_ring = 'Jhakri Ring',
    back = "Taranus's Cape",
  },
}
