return {
  ['default'] = {
    main = 'Marin Staff +1',
    sub = 'Umbra Strap',
    ammo = 'Ghastly Tathlum +1',
    head = 'Jhakri Coronal +2',
    body = 'Jhakri Robe +2',
    hands = 'Jhakri Cuffs +2',
    legs = 'Jhakri Slops +2',
    feet = "Herald's Gaiters",
    neck = 'Saevus Pendant +1',
    waist = 'Embla Sash',
    left_ear = 'Friomisi Earring',
    right_ear = 'Novio Earring',
    left_ring = 'Jhakri Ring',
    right_ring = 'Mallquis Ring',
    back = { name = 'Mecisto. Mantle', augments = { 'Cap. Point+49%', 'MND+1', 'Rng.Acc.+5', 'DEF+6' } },
  },
  ['refresh'] = {
    ammo = 'Ghastly Tathlum +1',
    head = 'Acad. Mortar. +1',
    body = 'Jhakri Robe +2',
    hands = 'Jhakri Cuffs +2',
    legs = 'Jhakri Slops +2',
    feet = "Herald's Gaiters",
    neck = 'Saevus Pendant +1',
    waist = 'Embla Sash',
    left_ear = 'Friomisi Earring',
    right_ear = 'Novio Earring',
    left_ring = 'Mallquis Ring',
    right_ring = 'Jhakri Ring',
    back = "Taranus's Cape",
  },
}
