return {
  ['Elemental Magic'] = {
    default = {
      ammo = 'Ghastly Tathlum +1',
      head = 'Jhakri Coronal +2',
      body = 'Jhakri Robe +2',
      hands = 'Jhakri Cuffs +2',
      legs = 'Jhakri Slops +2',
      feet = 'Jhakri Pigaches +2',
      neck = 'Saevus Pendant +1',
      waist = 'Witful Belt',
      left_ear = 'Friomisi Earring',
      right_ear = 'Novio Earring',
      left_ring = 'Acumen Ring',
      right_ring = 'Jhakri Ring',
      back = { name = 'Mecisto. Mantle', augments = { 'Cap. Point+49%', 'MND+1', 'Rng.Acc.+5', 'DEF+6' } },
    },
    burst = {
      ammo = 'Ghastly Tathlum +1',
      head = 'Jhakri Coronal +2',
      body = 'Jhakri Robe +2',
      hands = 'Jhakri Cuffs +2',
      legs = 'Mallquis Trews +1',
      feet = 'Jhakri Pigaches +2',
      neck = 'Saevus Pendant +1',
      waist = 'Witful Belt',
      left_ear = 'Friomisi Earring',
      right_ear = 'Novio Earring',
      left_ring = 'Mallquis Ring',
      right_ring = 'Jhakri Ring',
    },
    spells = {},
  },
  ['Dark Magic'] = {
    default = {
      ammo = 'Ghastly Tathlum +1',
      head = 'Jhakri Coronal +2',
      body = 'Jhakri Robe +2',
      hands = 'Jhakri Cuffs +2',
      legs = 'Jhakri Slops +2',
      feet = 'Jhakri Pigaches +2',
      neck = "Sorcerer's Stole",
      waist = 'Witful Belt',
      left_ear = 'Friomisi Earring',
      right_ear = 'Novio Earring',
      left_ring = 'Mallquis Ring',
      right_ring = 'Jhakri Ring',
      back = "Taranus's Cape",
    },
    spells = {
      ['Aspir'] = {
        left_ring = 'Excelsis Ring',
      },
      ['Drain'] = 'Aspir',
    },
  },
  ['Enfeebling Magic'] = {
    default = {
      ammo = 'Ghastly Tathlum +1',
      head = 'Jhakri Coronal +2',
      body = 'Jhakri Robe +2',
      hands = 'Jhakri Cuffs +2',
      legs = 'Jhakri Slops +2',
      feet = 'Jhakri Pigaches +2',
      neck = 'Loricate Torque',
      waist = 'Witful Belt',
      left_ear = 'Friomisi Earring',
      right_ear = 'Novio Earring',
      left_ring = 'Perception Ring',
      right_ring = 'Jhakri Ring',
      back = "Taranus's Cape",
    },
    spells = {},
  },
  ['Healing Magic'] = {
    default = {
      ammo = 'Ghastly Tathlum +1',
      head = 'Jhakri Coronal +2',
      body = 'Jhakri Robe +2',
      hands = 'Jhakri Cuffs +2',
      legs = 'Jhakri Slops +2',
      feet = 'Jhakri Pigaches +2',
      neck = 'Loricate Torque',
      waist = 'Witful Belt',
      left_ear = 'Friomisi Earring',
      right_ear = 'Novio Earring',
      left_ring = 'Perception Ring',
      right_ring = 'Jhakri Ring',
      back = "Taranus's Cape",
    },
    spells = {},
  },
  ['Enhancing Magic'] = {
    default = {
      ammo = 'Ghastly Tathlum +1',
      head = 'Jhakri Coronal +2',
      body = 'Jhakri Robe +2',
      hands = 'Jhakri Cuffs +2',
      legs = 'Jhakri Slops +2',
      feet = 'Jhakri Pigaches +2',
      neck = 'Loricate Torque',
      waist = 'Witful Belt',
      left_ear = 'Friomisi Earring',
      right_ear = 'Novio Earring',
      left_ring = 'Perception Ring',
      right_ring = 'Jhakri Ring',
      back = "Taranus's Cape",
    },
    spells = {},
  },
}
