return {
  default = {
    ammo = 'Knobkierrie',
    head = 'Nyame Helm',
    body = 'Nyame Mail',
    hands = 'Nyame Gauntlets',
    legs = 'Nyame Flanchard',
    feet = 'Sulev. Leggings +2',
    neck = 'Fotia Gorget',
    waist = 'Fotia Belt',
    left_ear = 'Moonshade Earring',
    right_ear = 'Thrud Earring',
    left_ring = 'Hetairoi Ring',
    right_ring = 'Petrov Ring',
    back = { name = 'Mecisto. Mantle', augments = { 'Cap. Point+49%', 'MND+1', 'Rng.Acc.+5', 'DEF+6' } },
  },
  ["Ukko's  Fury"] = {
    ammo = 'Knobkierrie',
    head = 'Flam. Zucchetto +2',
    body = "Sakpata's Plate",
    hands = 'Flam. Manopolas +2',
    legs = "Sakpata's Cuisses",
    feet = "Sakpata's Leggings",
    neck = 'Lissome Necklace',
    waist = 'Sailfi Belt +1',
    left_ear = 'Brutal Earring',
    right_ear = 'Moonshade Earring',
    left_ring = 'Hetairoi Ring',
    right_ring = 'Karieyh Ring',
    back = { name = 'Mecisto. Mantle', augments = { 'Cap. Point+49%', 'MND+1', 'Rng.Acc.+5', 'DEF+6' } },
  },
  ['Upheaval'] = {
    ['Multi'] = {
      ammo = 'Ginsen',
      head = 'Flam. Zucchetto +2',
      body = "Sakpata's Plate",
      hands = 'Sulev. Gauntlets +2',
      legs = 'Sulev. Cuisses +2',
      feet = 'Flam. Gambieras +2',
      neck = 'Lissome Necklace',
      waist = 'Fotia Belt',
      left_ear = 'Brutal Earring',
      right_ear = 'Mache Earring',
      left_ring = 'Hetairoi Ring',
      right_ring = 'Petrov Ring',
      back = { name = 'Mecisto. Mantle', augments = { 'Cap. Point+49%', 'MND+1', 'Rng.Acc.+5', 'DEF+6' } },
    },
    ['WSD'] = {
      ammo = 'Knobkierrie',
      head = 'Nyame Helm',
      body = 'Nyame Mail',
      hands = 'Nyame Gauntlets',
      legs = 'Nyame Flanchard',
      feet = 'Sulev. Leggings +2',
      neck = 'Lissome Necklace',
      waist = 'Sailfi Belt +1',
      left_ear = 'Moonshade Earring',
      right_ear = 'Thrud Earring',
      left_ring = 'Karieyh Ring',
      right_ring = 'Petrov Ring',
      back = { name = 'Mecisto. Mantle', augments = { 'Cap. Point+49%', 'MND+1', 'Rng.Acc.+5', 'DEF+6' } },
    },
  },
}
