return {
    main = { name = "Ichigohitofuri", augments = { 'DMG:+30', 'STR+20', 'Accuracy+15', } },
    sub = "Nepenthe Grip",
    ammo = "Ginsen",
    head = "Flam. Zucchetto +1",
    body = "Hachiryu Haramaki",
    hands = "Wakido Kote",
    legs = "Hiza. Hizayoroi +1",
    feet = "Flam. Gambieras +1",
    neck = "Samurai's Nodowa",
    waist = "Sailfi Belt +1",
    left_ear = "Mache Earring",
    right_ear = "Brutal Earring",
    left_ring = "Petrov Ring",
    right_ring = "Rajas Ring",
    back = { name = "Mecisto. Mantle", augments = { 'Cap. Point+49%', 'MND+1', 'Rng.Acc.+5', 'DEF+6', } },
}
