return {
  ['dt'] = {
    ammo = 'Ginsen',
    head = 'Nyame Helm',
    body = 'Nyame Mail',
    hands = 'Nyame Gauntlets',
    legs = 'Nyame Flanchard',
    feet = 'Nyame Sollerets',
    neck = 'Loricate Torque',
    waist = 'Ioskeha Belt',
    left_ear = 'Mache Earring',
    right_ear = 'Brutal Earring',
    left_ring = 'Petrov Ring',
    right_ring = 'Karieyh Ring',
    back = 'Abyss Cape',
  },
  ['speed'] = {
    ammo = 'Ginsen',
    head = 'Nyame Helm',
    body = 'Nyame Mail',
    hands = 'Nyame Gauntlets',
    legs = { name = 'Carmine Cuisses +1', augments = { 'Accuracy+20', 'Attack+12', '"Dual Wield"+6' } },
    feet = 'Nyame Sollerets',
    neck = 'Loricate Torque',
    waist = 'Ioskeha Belt',
    left_ear = 'Mache Earring',
    right_ear = 'Brutal Earring',
    left_ring = 'Petrov Ring',
    right_ring = 'Karieyh Ring',
    back = 'Abyss Cape',
  },
}
