return {
  ['dt'] = {
    ammo = 'Ginsen',
    head = "Sakpata's Helm",
    body = "Sakpata's Plate",
    hands = "Sakpata's Gauntlets",
    legs = "Sakpata's Cuisses",
    feet = "Sakpata's Leggings",
    neck = 'Loricate Torque',
    waist = 'Ioskeha Belt',
    left_ear = 'Mache Earring',
    right_ear = 'Brutal Earring',
    left_ring = "Sulevia's Ring",
    right_ring = 'Gelatinous Ring',
    back = 'Grounded Mantle',
  },
  ['speed'] = {
    ammo = 'Ginsen',
    head = "Sakpata's Helm",
    body = "Sakpata's Plate",
    hands = "Sakpata's Gauntlets",
    legs = { name = 'Carmine Cuisses +1', augments = { 'Accuracy+20', 'Attack+12', '"Dual Wield"+6' } },
    feet = "Sakpata's Leggings",
    neck = 'Loricate Torque',
    waist = 'Ioskeha Belt',
    left_ear = 'Mache Earring',
    right_ear = 'Brutal Earring',
    left_ring = "Sulevia's Ring",
    right_ring = 'Gelatinous Ring',
    back = 'Grounded Mantle',
  },
}
