return {
  ['default'] = {
    ammo = 'Knobkierrie',
    head = 'Nyame Helm',
    body = 'Nyame Mail',
    hands = 'Nyame Gauntlets',
    legs = 'Nyame Flanchard',
    feet = 'Sulev. Leggings +2',
    neck = 'Sanctity Necklace',
    waist = 'Ioskeha Belt',
    left_ear = 'Thrud Earring',
    right_ear = 'Moonshade Earring',
    left_ring = "Sulevia's Ring",
    right_ring = 'Karieyh Ring',
  },
  ['Resolution'] = {
    ammo = 'Knobkierrie',
    head = 'Flam. Zucchetto +2',
    body = 'Nyame Mail',
    hands = 'Nyame Gauntlets',
    legs = 'Ig. Flanchard +2',
    feet = 'Sulev. Leggings +1',
    neck = 'Sanctity Necklace',
    waist = 'Ioskeha Belt',
    left_ear = 'Mache Earring',
    right_ear = 'Brutal Earring',
    left_ring = 'Petrov Ring',
    right_ring = 'Karieyh Ring',
  },
}
