return {
  ['default'] = {
    ammo = 'Knobkierrie',
    head = 'Nyame Helm',
    body = 'Nyame Mail',
    hands = 'Nyame Gauntlets',
    legs = 'Nyame Flanchard',
    feet = 'Sulev. Leggings +1',
    neck = 'Sanctity Necklace',
    left_ear = 'Thrud Earring',
    right_ear = {
      name = 'Heath. Earring +1',
      augments = { 'System: 1 ID: 1676 Val: 0', 'Accuracy+12', 'Mag. Acc.+12', 'Weapon skill damage +2%' },
    },
    right_ring = 'Karieyh Ring',
    back = 'Abyss Cape',
  },
  ['Resolution'] = {
    ammo = 'Knobkierrie',
    head = 'Flam. Zucchetto +2',
    body = 'Nyame Mail',
    hands = 'Nyame Gauntlets',
    legs = 'Ig. Flanchard +2',
    feet = 'Sulev. Leggings +1',
    neck = 'Sanctity Necklace',
    waist = 'Ioskeha Belt',
    left_ear = 'Mache Earring',
    right_ear = 'Brutal Earring',
    left_ring = 'Petrov Ring',
    right_ring = 'Karieyh Ring',
  },
}
