return {
  ['default'] = {
    ammo = "Ginsen",
    head = "Sulevia's Mask +2",
    body = "Sulevia's Plate. +2",
    hands = "Sulev. Gauntlets +1",
    legs = "Sulevi. Cuisses +1",
    feet = "Sulev. Leggings +1",
    neck = "Loricate Torque",
    waist = "Sailfi Belt +1",
    left_ear = "Mache Earring",
    right_ear = "Brutal Earring",
    left_ring = "Flamma Ring",
    right_ring = "Sulevia's Ring",
  },
  ['default speed'] = {
    ammo = "Ginsen",
    head = "Sulevia's Mask +2",
    body = "Sulevia's Plate. +2",
    hands = "Sulev. Gauntlets +1",
    legs = { name = 'Carmine Cuisses +1', augments = { 'Accuracy+20', 'Attack+12', '"Dual Wield"+6' } },
    feet = "Sulev. Leggings +1",
    neck = "Loricate Torque",
    waist = "Sailfi Belt +1",
    left_ear = "Mache Earring",
    right_ear = "Brutal Earring",
    left_ring = "Flamma Ring",
    right_ring = "Sulevia's Ring",
  },
}
