return {
  ['default'] = {
    ammo = 'Ghastly Tathlum +1',
    head = 'Nyame Helm',
    body = 'Nyame Mail',
    hands = 'Nyame Gauntlets',
    legs = 'Nyame Flanchard',
    feet = 'Nyame Sollerets',
    neck = 'Loricate Torque',
    waist = 'Witful Belt',
    left_ear = "Hecate's Earring",
    right_ear = 'Moldavite Earring',
    left_ring = 'Mallquis Ring',
    right_ring = 'Jhakri Ring',
    back = "Taranus's Cape",
  },
  ['refresh'] = {
    ammo = 'Ghastly Tathlum +1',
    head = 'Jhakri Coronal +2',
    body = 'Jhakri Robe +2',
    hands = 'Jhakri Cuffs +2',
    legs = 'Jhakri Slops +2',
    feet = 'Jhakri Pigaches +2',
    neck = 'Loricate Torque',
    waist = 'Witful Belt',
    left_ear = "Hecate's Earring",
    right_ear = 'Moldavite Earring',
    left_ring = 'Mallquis Ring',
    right_ring = 'Jhakri Ring',
    back = "Taranus's Cape",
  },
  ['refresh speed'] = {
    ammo = 'Ghastly Tathlum +1',
    head = 'Jhakri Coronal +2',
    body = 'Jhakri Robe +2',
    hands = 'Jhakri Cuffs +2',
    legs = 'Jhakri Slops +2',
    feet = 'Jhakri Pigaches +2',
    neck = 'Loricate Torque',
    waist = 'Witful Belt',
    left_ear = "Hecate's Earring",
    right_ear = 'Moldavite Earring',
    left_ring = 'Mallquis Ring',
    right_ring = 'Jhakri Ring',
    back = "Taranus's Cape",
  },
}
