return {
  ['Elemental Magic'] = {
    default = {
      ammo = 'Ghastly Tathlum +1',
      head = 'Jhakri Coronal +2',
      body = "Spaekona's Coat +2",
      hands = 'Jhakri Cuffs +2',
      legs = 'Jhakri Slops +2',
      feet = 'Jhakri Pigaches +2',
      neck = 'Sanctity Necklace',
      waist = 'Witful Belt',
      right_ear = 'Friomisi Earring',
      left_ring = 'Mallquis Ring',
      left_ring = 'Acumen Ring',
      right_ring = 'Jhakri Ring',
      back = { name = 'Bane Cape', augments = { 'Elem. magic skill +3', 'Dark magic skill +6' } },
    },
    burst = {
      ammo = 'Ghastly Tathlum +1',
      head = 'Jhakri Coronal +2',
      body = "Spaekona's Coat +2",
      hands = 'Jhakri Cuffs +2',
      legs = 'Mallquis Trews +1',
      feet = 'Jhakri Pigaches +2',
      neck = 'Sanctity Necklace',
      waist = 'Witful Belt',
      right_ear = 'Friomisi Earring',
      left_ring = 'Mallquis Ring',
      left_ring = 'Mallquis Ring',
      right_ring = 'Jhakri Ring',
      back = "Taranus's Cape",
    },
    spells = {},
  },
  ['Dark Magic'] = {
    default = {
      ammo = 'Ghastly Tathlum +1',
      head = 'Jhakri Coronal +2',
      body = 'Spae. Coat +2',
      -- body = "Jhakri Robe +2",
      hands = 'Goetia Gloves +1',
      legs = 'Jhakri Slops +2',
      feet = 'Jhakri Pigaches +2',
      neck = "Sorcerer's Stole",
      waist = 'Witful Belt',
      left_ear = "Hecate's Earring",
      right_ear = 'Moldavite Earring',
      left_ring = 'Mallquis Ring',
      right_ring = 'Jhakri Ring',
      back = "Taranus's Cape",
    },
    spells = {
      ['Aspir'] = {
        left_ring = 'Excelsis Ring',
      },
      ['Drain'] = 'Aspir',
    },
  },
  ['Enfeebling Magic'] = {
    default = {
      ammo = 'Ghastly Tathlum +1',
      head = 'Jhakri Coronal +2',
      body = 'Jhakri Robe +2',
      hands = 'Jhakri Cuffs +2',
      legs = 'Jhakri Slops +2',
      feet = 'Jhakri Pigaches +2',
      neck = 'Loricate Torque',
      waist = 'Witful Belt',
      left_ear = "Hecate's Earring",
      right_ear = 'Moldavite Earring',
      left_ring = 'Perception Ring',
      right_ring = 'Jhakri Ring',
      back = "Taranus's Cape",
    },
    spells = {},
  },
  ['Healing Magic'] = {
    default = {
      ammo = 'Ghastly Tathlum +1',
      head = 'Jhakri Coronal +2',
      body = 'Jhakri Robe +2',
      hands = 'Jhakri Cuffs +2',
      legs = 'Jhakri Slops +2',
      feet = 'Jhakri Pigaches +2',
      neck = 'Loricate Torque',
      waist = 'Witful Belt',
      left_ear = "Hecate's Earring",
      right_ear = 'Moldavite Earring',
      left_ring = 'Perception Ring',
      right_ring = 'Jhakri Ring',
      back = "Taranus's Cape",
    },
    spells = {},
  },
  ['Enhancing Magic'] = {
    default = {
      ammo = 'Ghastly Tathlum +1',
      head = 'Jhakri Coronal +2',
      body = 'Jhakri Robe +2',
      hands = 'Jhakri Cuffs +2',
      legs = 'Jhakri Slops +2',
      feet = 'Jhakri Pigaches +2',
      neck = 'Loricate Torque',
      waist = 'Witful Belt',
      left_ear = "Hecate's Earring",
      right_ear = 'Moldavite Earring',
      left_ring = 'Perception Ring',
      right_ring = 'Jhakri Ring',
      back = "Taranus's Cape",
    },
    spells = {},
  },
}
