return {
  ['default'] = {
    main = 'Naegling',
    ammo = 'Bullet',
    head = 'Meghanada Visor',
    body = 'Meghanada Cuirie',
    hands = 'Meghanada Gloves',
    legs = 'Meg. Chausses',
    feet = 'Meg. Jambeaux',
    neck = 'Loricate Torque',
    waist = 'Sailfi Belt +1',
    left_ear = 'Brutal Earring',
    right_ear = 'Mache Earring',
    left_ring = 'Rajas Ring',
    right_ring = 'Petrov Ring',
    back = { name = 'Mecisto. Mantle', augments = { 'Cap. Point+49%', 'MND+1', 'Rng.Acc.+5', 'DEF+6' } },
  },
  ['refresh'] = {
    main = 'Naegling',
    ammo = 'Bullet',
    head = 'Meghanada Visor',
    body = 'Meghanada Cuirie',
    hands = 'Meghanada Gloves',
    legs = 'Meg. Chausses',
    feet = 'Meg. Jambeaux',
    neck = 'Loricate Torque',
    waist = 'Sailfi Belt +1',
    left_ear = 'Brutal Earring',
    right_ear = 'Mache Earring',
    left_ring = 'Rajas Ring',
    right_ring = 'Petrov Ring',
    back = { name = 'Mecisto. Mantle', augments = { 'Cap. Point+49%', 'MND+1', 'Rng.Acc.+5', 'DEF+6' } },
  },
  ['refresh speed'] = {

    ammo = 'Bullet',
    head = 'Meghanada Visor',
    body = 'Meghanada Cuirie',
    hands = 'Meghanada Gloves',
    legs = { name = 'Carmine Cuisses +1', augments = { 'Accuracy+20', 'Attack+12', '"Dual Wield"+6' } },
    feet = 'Meg. Jambeaux',
    neck = 'Loricate Torque',
    waist = 'Sailfi Belt +1',
    left_ear = 'Brutal Earring',
    right_ear = 'Mache Earring',
    left_ring = 'Rajas Ring',
    right_ring = 'Petrov Ring',
    back = { name = 'Mecisto. Mantle', augments = { 'Cap. Point+49%', 'MND+1', 'Rng.Acc.+5', 'DEF+6' } },
  },
}
