return {
	["default"] = {
		ammo = "Kalboron Stone",
		head = "Leth. Chappel +2",
		body = "Lethargy Sayon +2",
		hands = "Leth. Ganth. +2",
		legs = "Nyame Flanchard",
		feet = "Nyame Sollerets",
		neck = "Loricate Torque",
		waist = "Sailfi Belt +1",
		left_ear = "Loquac. Earring",
		right_ear = "Brutal Earring",
		left_ring = "Ayanmo Ring",
		right_ring = "Jhakri Ring",
		back = {
			name = "Sucellos's Cape",
			augments = { "DEX+20", "Accuracy+20 Attack+20", "Accuracy+10", '"Dbl.Atk."+10', "Damage taken-5%" },
		},
	},
	["refresh"] = {
		ammo = "Ginsen",
		head = "Viti. Chapeau +1",
		body = "Atrophy Tabard +3",
		hands = "Aya. Manopolas +2",
		legs = "Leth. Fuseau +2",
		feet = "Aya. Gambieras +2",
		neck = "Sanctity Necklace",
		waist = "Sailfi Belt +1",
		left_ear = "Mache Earring",
		right_ear = "Brutal Earring",
		left_ring = "Ayanmo Ring",
		right_ring = "Karieyh Ring",
		back = {
			name = "Sucellos's Cape",
			augments = { "DEX+20", "Accuracy+20 Attack+20", "Accuracy+10", '"Dbl.Atk."+10', "Damage taken-5%" },
		},
	},
	["refresh speed"] = {
		ammo = "Ginsen",
		head = "Viti. Chapeau +1",
		body = "Atrophy Tabard +3",
		hands = "Aya. Manopolas +2",
		legs = { name = "Carmine Cuisses +1", augments = { "Accuracy+20", "Attack+12", '"Dual Wield"+6' } },
		feet = "Aya. Gambieras +2",
		neck = "Sanctity Necklace",
		waist = "Sailfi Belt +1",
		left_ear = "Mache Earring",
		right_ear = "Brutal Earring",
		left_ring = "Ayanmo Ring",
		right_ring = "Karieyh Ring",
		back = {
			name = "Sucellos's Cape",
			augments = { "DEX+20", "Accuracy+20 Attack+20", "Accuracy+10", '"Dbl.Atk."+10', "Damage taken-5%" },
		},
	},
}
