return {
  ['default'] = {
    ammo = 'Ginsen',
    head = 'Viti. Chapeau +2',
    body = 'Atrophy Tabard +3',
    hands = 'Atrophy Gloves +3',
    legs = 'Jhakri Slops +2',
    feet = 'Jhakri Pigaches +2',
    neck = 'Sanctity Necklace',
    waist = 'Sailfi Belt +1',
    left_ear = 'Moonshade Earring',
    right_ear = 'Mache Earring',
    left_ring = 'Petrov Ring',
    right_ring = 'Karieyh Ring',
    back = {
      name = "Sucellos's Cape",
      augments = { 'DEX+20', 'Accuracy+20 Attack+20', 'Accuracy+10', '"Dbl.Atk."+10', 'Damage taken-5%' },
    },
  },
  ['Savage Blade'] = {
    ammo = 'Ginsen',
    head = 'Viti. Chapeau +2',
    body = 'Nyame Mail',
    hands = 'Atrophy Gloves +3',
    legs = 'Nyame Flanchard',
    feet = 'Leth. Houseaux +2',
    neck = 'Lissome Necklace',
    waist = 'Sailfi Belt +1',
    left_ear = 'Brutal Earring',
    right_ear = 'Moonshade Earring',
    left_ring = 'Petrov Ring',
    right_ring = 'Karieyh Ring',
    back = {
      name = "Sucellos's Cape",
      augments = {
        'STR+20',
        'Accuracy+20 Attack+20',
        'STR+5',
        'Weapon skill damage +10%',
      },
    },
  },
  ['Requiescat'] = {
    ammo = 'Ginsen',
    head = 'Jhakri Coronal +2',
    body = 'Jhakri Robe +2',
    hands = 'Atrophy Gloves +3',
    legs = 'Jhakri Slops +2',
    feet = 'Jhakri Pigaches +2',
    neck = 'Fotia Gorget',
    waist = 'Fotia Belt',
    left_ear = 'Moonshade Earring',
    right_ear = 'Brutal Earring',
    left_ring = 'Hetairoi Ring',
    right_ring = 'Karieyh Ring',
    back = {
      name = "Sucellos's Cape",
      augments = {
        'MND+20',
        'Mag. Acc+20 /Mag. Dmg.+20',
        'Mag. Acc.+10',
        '"Fast Cast"+10',
      },
    },
  },
  ['Chant du Cygne'] = {
    ammo = 'Ginsen',
    head = 'Atrophy Chapeau +3',
    body = 'Ayanmo Corazza +2',
    hands = 'Atrophy Gloves +3',
    legs = 'Aya. Cosciales +2',
    feet = 'Leth. Houseaux +2',
    neck = 'Fotia Gorget',
    waist = 'Fotia Belt',
    left_ear = 'Moonshade Earring',
    right_ear = 'Mache Earring',
    left_ring = 'Petrov Ring',
    right_ring = 'Karieyh Ring',
    back = {
      name = "Sucellos's Cape",
      augments = { 'DEX+20', 'Accuracy+20 Attack+20', 'Accuracy+10', '"Dbl.Atk."+10', 'Damage taken-5%' },
    },
  },
}
