return {
  ['default'] = {
    ammo = 'Ginsen',
    head = "Sakpata's Helm",
    body = "Sakpata's Plate",
    hands = "Sakpata's Gauntlets",
    legs = 'Chev. Cuisses +2',
    feet = "Sakpata's Leggings",
    neck = 'Loricate Torque',
    waist = 'Creed Baudrier',
    left_ear = 'Brutal Earring',
    right_ear = 'Mache Earring',
    left_ring = 'Gelatinous Ring',
    right_ring = "Sulevia's Ring",
    back = { name = "Rudianos's Mantle", augments = { 'HP+60', 'Eva.+20 /Mag. Eva.+20', 'Enmity+10' } },
  },
  ['default speed'] = {
    ammo = 'Ginsen',
    head = "Sakpata's Helm",
    body = "Sakpata's Plate",
    hands = "Sakpata's Gauntlets",
    legs = { name = 'Carmine Cuisses +1', augments = { 'Accuracy+20', 'Attack+12', '"Dual Wield"+6' } },
    feet = "Sakpata's Leggings",
    neck = 'Loricate Torque',
    waist = 'Creed Baudrier',
    left_ear = 'Brutal Earring',
    right_ear = 'Mache Earring',
    left_ring = 'Gelatinous Ring',
    right_ring = "Sulevia's Ring",
    back = { name = "Rudianos's Mantle", augments = { 'HP+60', 'Eva.+20 /Mag. Eva.+20', 'Enmity+10' } },
  },
}
