return {
  ['default'] = {
    body = { name = 'Rev. Surcoat +3', priority = 13 },
    hands = {
      name = 'Souv. Handsch. +1',
      augments = { 'HP+105', 'Enmity+9', 'Potency of "Cure" effect received +15%' },
      priority = 12,
    },
    head = { name = 'Chev. Armet +2', priority = 11 },
    legs = { name = 'Chev. Cuisses +2', priority = 10 },
    right_ring = { name = "K'ayres Ring", priority = 9 },
    feet = { name = "Sakpata's Leggings", priority = 8 },
    back = { name = "Rudianos's Mantle", augments = { 'HP+60', 'Eva.+20 /Mag. Eva.+20', 'Enmity+10' }, priority = 7 },
    left_ear = { name = 'Cryptic Earring', priority = 6 },
    left_ring = { name = 'Supershear Ring', priority = 5 },
    waist = { name = 'Sailfi Belt +1', priority = 4 },
    right_ear = {
      name = 'Chev. Earring +1',
      augments = { 'System: 1 ID: 1676 Val: 0', 'Accuracy+15', 'Mag. Acc.+15', 'Damage taken-5%' },
      priority = 3,
    },
    neck = { name = 'Loricate Torque', priority = 2 },
    ammo = { name = 'Staunch Tathlum', priority = 1 },
  },
  ['default speed'] = {
    body = { name = 'Rev. Surcoat +3', priority = 13 },
    hands = {
      name = 'Souv. Handsch. +1',
      augments = { 'HP+105', 'Enmity+9', 'Potency of "Cure" effect received +15%' },
      priority = 12,
    },
    head = { name = 'Chev. Armet +2', priority = 11 },
    right_ring = { name = "K'ayres Ring", priority = 10 },
    feet = { name = "Sakpata's Leggings", priority = 9 },
    back = { name = "Rudianos's Mantle", augments = { 'HP+60', 'Eva.+20 /Mag. Eva.+20', 'Enmity+10' }, priority = 8 },
    legs = { name = 'Carmine Cuisses +1', augments = { 'Accuracy+20', 'Attack+12', '"Dual Wield"+6' }, priority = 7 },
    left_ear = { name = 'Cryptic Earring', priority = 6 },
    left_ring = { name = 'Supershear Ring', priority = 5 },
    waist = { name = 'Sailfi Belt +1', priority = 4 },
    right_ear = {
      name = 'Chev. Earring +1',
      augments = { 'System: 1 ID: 1676 Val: 0', 'Accuracy+15', 'Mag. Acc.+15', 'Damage taken-5%' },
      priority = 3,
    },
    neck = { name = 'Loricate Torque', priority = 2 },
    ammo = { name = 'Staunch Tathlum', priority = 1 },
  },
}
